language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
  
install:
  - 'pip install pipenv'
  - 'pipenv install --dev'

script: 
  - 'flake8 ./*/*.py'
  - 'flake8 ./*.py'
  - 'python -m pytest --cov=. --cov-report=xml'  

